version: "3"

services:
  flask:
    build: .
    container_name: flask_application
    ports:
      - 5000:5000
    env_file:
      - ./app/.env
    command:
      - sh
      - -c
      - |
        python main.py --host=0.0.0.0:5000
    volumes:
      - ./app:/app
